version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "74:2e:2c:7b:91:e6:3a:16:cb:d6:ed:ba:d1:54:63:05"
      - checkout
      - restore_cache:
          keys:
            - dependencies_wuohoo.github.io
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_wuohoo.github.io
      - run:
          name: Build
          command: yarn docs:build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy to Github pages
          command: ./scripts/deploy.sh